---
kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: modia-soap-til-rest-proxy
  namespace: default
  labels:
    team: personoversikt
spec:
  image: "{{image}}"
  ingresses:
    - https://modia-soap-til-rest-proxy.nais.adeo.no/modia-soap-til-rest-proxy
    - https://app.adeo.no/modia-soap-til-rest-proxy
  port: 8080
  liveness:
    path: modia-soap-til-rest-proxy/internal/isAlive
    initialDelay: 60
  readiness:
    path: modia-soap-til-rest-proxy/internal/isReady
    initialDelay: 60
  prometheus:
    enabled: true
    path: modia-soap-til-rest-proxy/internal/prometheus
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 3000m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 768Mi
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvmodia-soap-til-rest-proxy
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /apikey/appdynamics/prod
        mountPath: /var/run/secrets/nais.io/vault
  env:
    - name: SECURITYTOKENSERVICE_URL
      value: "https://sts.adeo.no/SecurityTokenServiceProvider/"
    - name: ISSO_HOST_URL
      value: "https://isso.adeo.no/isso/oauth2"
    - name: ISSO_JWKS_URL
      value: "https://isso.adeo.no/isso/oauth2/connect/jwk_uri"
    - name: ISSO_ISSUER_URL
      value: "https://isso.adeo.no:443/isso/oauth2"
    - name: ISSO_ISALIVE_URL
      value: "https://isso.adeo.no/isso/isAlive.jsp"
    - name: ABAC_PDP_ENDPOINT_URL
      value: "https://wasapp.adeo.no/asm-pdp/authorize"
    - name: OIDC_REDIRECT_URL
      value: "https://app.adeo.no/veilarblogin/api/login"
    - name: SECURITY_TOKEN_SERVICE_TOKEN_URL
      value: "https://security-token-service.nais.adeo.no/rest/v1/sts/token"
    - name: HENVENDELSESARKIV_ARKIVPOST_URL
      value: "https://henvendelsesarkiv2.nais.adeo.no/arkivpost"
    - name: HENVENDELSESARKIV_TEMAGRUPPER_URL
      value: "https://henvendelsesarkiv2.nais.adeo.no/temagrupper"
