---
kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: modia-soap-til-rest-proxy
  namespace: "{{ namespace }}"
  labels:
    team: personoversikt
spec:
  image: "{{image}}"
  ingresses:
  - https://modia-soap-til-rest-proxy-{{ namespace }}.nais.preprod.local/modia-soap-til-rest-proxy
  - https://app-{{ namespace }}.adeo.no/modia-soap-til-rest-proxy
  port: 8080
  liveness:
    path: modia-soap-til-rest-proxy/internal/isAlive
    initialDelay: 60
  readiness:
    path: modia-soap-til-rest-proxy/internal/isReady
    initialDelay: 60
  prometheus:
    enabled: true
    path: modia-soap-til-rest-proxy/internal/prometheus
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 3000m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 768Mi
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvmodia-soap-til-rest-proxy
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /apikey/appdynamics/dev
        mountPath: /var/run/secrets/nais.io/vault
  env:
    - name: ISSO_CLIENT_ID
      value: "veilarblogin-{{ namespace }}"
    - name: ISSO_DISCOVERY_URL
      value: "https://isso-q.adeo.no/isso/oauth2/.well-known/openid-configuration"
    - name: ISSO_REFRESH_URL
      value: "https://app-{{ namespace }}.adeo.no/veilarblogin/api/openam-refresh"
    - name: SECURITY_TOKEN_SERVICE_TOKEN_URL
      value: "https://security-token-service.nais.preprod.local/rest/v1/sts/token"
    - name: HENVENDELSESARKIV_ARKIVPOST_URL
      value: "https://henvendelsesarkiv2-{{ namespace }}.nais.preprod.local/arkivpost"
    - name: HENVENDELSESARKIV_TEMAGRUPPER_URL
      value: "https://henvendelsesarkiv2-{{ namespace }}.nais.preprod.local/temagrupper"
